volumes:
  db_data:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306 # You might want to change this if MySQL is already running
    volumes:
      - db_data:/var/lib/mysql