volumes:
  db_data:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306 # You might want to change this if MariaDB is already running
    volumes:
      - db_data:/var/lib/mysql